'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace SalaryReports.UserControls

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class PrintRibbonControllerResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(SalaryReports.UserControls.PrintRibbonControllerResources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SalaryReports.UserControls.PrintRibbonControllerResources", GetType(SalaryReports.UserControls.PrintRibbonControllerResources).Assembly)
                    SalaryReports.UserControls.PrintRibbonControllerResources.resourceMan = temp
                End If

                Return SalaryReports.UserControls.PrintRibbonControllerResources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Customize As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Customize", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Document As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Document", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFile", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMht", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXls", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackground", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Find As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Find", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FindLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_HandTool As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_HandTool", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Magnifier", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Open As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Open", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMargins", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3 As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4 As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5 As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6 As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSize", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Parameters As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Parameters", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Pointer As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Pointer", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Print As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Print", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Save As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Save", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Scale As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Scale", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsv", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFile", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMht", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdf", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtf", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxt", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXls", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Watermark As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Watermark", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Zoom As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Zoom", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = SalaryReports.UserControls.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", SalaryReports.UserControls.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
